//===- CanonTableGen.cpp -------------------------------------------------===//
//
// Copyright 2026 Advanced Micro Devices, Inc.
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implements a TableGen backend that walks every `SalmonOp`
// record in `amd/salmon/td/SalmonAMDGCN.td` and emits the static
// `kCanonTable[]` array consumed by `OpcodeMap::build`. Each row is the
// pair `{AMDGPU::<inst-record-name>, SemOp::<sem-string>}`.
//
// `SalmonOp` is a Salmon-side decorator class on top of LLVM's
// `Instruction`. By moving the table into TableGen we get:
//
//   * Type-checked family expansion via `multiclass` + `!cast<Instruction>`
//     on the Salmon side (`SalmonMUBUF4`, `SalmonSMEM3`, ...).
//   * A single source of truth that other `salmon-tblgen` backends can
//     iterate without rebuilding their own list of supported opcodes.
//   * A natural place for additional per-instruction Salmon metadata
//     (handler hints, gfx-rev gating, conformance tags) to grow as
//     extra fields on `SalmonOp`.
//
// The semantics of the emitted table match the previous hand-rolled
// `kCanonTable[]` exactly: when the same `Instruction` is bound to two
// `SemOp` strings, the *first* binding in source order wins (matches the
// runtime's `DenseMap::try_emplace`). Suppressed duplicates are emitted
// as `// duplicate-of` comments next to the winning row so the
// generated header still surfaces the intended-but-superseded mapping.
//
//===----------------------------------------------------------------------===//

#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"

#include <algorithm>

using namespace llvm;

//===----------------------------------------------------------------------===//
// Command-line options
//===----------------------------------------------------------------------===//

static cl::OptionCategory canonCat("Salmon Canon Table Generator Options");

static cl::opt<std::string> canonNamespace(
    "amdgcn-canon-namespace",
    cl::desc("C++ namespace for the generated canon table (default: "
             "transpiler::amdgcn::canon)"),
    cl::cat(canonCat), cl::init("transpiler::amdgcn::canon"));

//===----------------------------------------------------------------------===//
// Helpers
//===----------------------------------------------------------------------===//

namespace {
/// One row, ready to emit.
struct Row {
  /// AMDGPU `Instruction` record name (e.g. `V_ADD_F32_e64`).
  StringRef opc;
  /// Salmon `SemOp` enumerator name (e.g. `V_ADD_F32`).
  StringRef sem;
  /// Source location of the `def : SalmonOp<...>` record, used for
  /// PrintFatalError diagnostics.
  SMLoc loc;
};
} // namespace

/// Read the `Inst` field on a `SalmonOp` record and return the underlying
/// `Instruction` record name.
static StringRef readInstName(const Record *rec) {
  const RecordVal *rv = rec->getValue("Inst");
  if (!rv)
    PrintFatalError(rec->getLoc(),
                    "SalmonOp record is missing required `Inst` field");
  const DefInit *di = dyn_cast_or_null<DefInit>(rv->getValue());
  if (!di)
    PrintFatalError(rec->getLoc(),
                    "SalmonOp.`Inst` must resolve to an Instruction record");
  return di->getDef()->getName();
}

/// Read the `Sem` string field on a `SalmonOp` record.
static StringRef readSemString(const Record *rec) {
  const RecordVal *rv = rec->getValue("Sem");
  if (!rv)
    PrintFatalError(rec->getLoc(),
                    "SalmonOp record is missing required `Sem` field");
  const StringInit *si = dyn_cast_or_null<StringInit>(rv->getValue());
  if (!si)
    PrintFatalError(rec->getLoc(), "SalmonOp.`Sem` must be a string literal");
  return si->getValue();
}

//===----------------------------------------------------------------------===//
// Code emission
//===----------------------------------------------------------------------===//

static void emitPrologue(raw_ostream &os, ArrayRef<StringRef> namespaces) {
  os << "//===- AMDGCN Salmon canon table (auto-generated) -*- C++ "
        "-*-===//\n"
     << "//\n"
     << "// Generated by `salmon-tblgen --gen-amdgcn-canon-table`.\n"
     << "// DO NOT EDIT.\n"
     << "//\n"
     << "//===---------------------------------------------------------------"
        "------===//\n\n"
     << "#ifndef AMDGCN_GEN_CANON_TABLE\n"
     << "#define AMDGCN_GEN_CANON_TABLE\n\n"
     << "// Pulls in the `AMDGPU::*` opcode enumerators emitted by the\n"
     << "// AMDGPU backend. The Salmon `SemOp` enum is provided by the\n"
     << "// translation unit that includes this header (opcode_map.cpp).\n"
     << "#include \"MCTargetDesc/AMDGPUMCTargetDesc.h\"\n\n";

  for (StringRef ns : namespaces)
    os << "namespace " << ns << " {\n";
  os << "\n";

  os << R"cpp(/// One row of the auto-generated canonical-opcode table. `opc` is the
/// AMDGPU pseudo / real opcode (after Salmon's `canonicalize` chain has
/// folded MC -> pseudo, e32 -> e64, SDWA/DPP -> base, FLAT SADDR ->
/// VADDR, ...) and `sem` is the Salmon SemOp tag the raiser dispatches
/// on.
struct Entry {
  unsigned opc;
  ::transpiler::SemOp sem;
};

)cpp";
}

static void emitTable(raw_ostream &os, ArrayRef<Row> rows,
                      ArrayRef<std::pair<Row, StringRef>> suppressed) {
  os << "/// Auto-generated canonical-opcode -> SemOp table. Order matches\n"
     << "/// the source order of `def : SalmonOp<...>` records in\n"
     << "/// `amd/salmon/td/SalmonAMDGCN.td`; consumers that build a\n"
     << "/// `DenseMap` via `try_emplace` get \"first-wins\" semantics.\n"
     << "inline constexpr Entry kEntries[] = {\n";
  for (const Row &r : rows) {
    os << "    {::llvm::AMDGPU::" << r.opc << ", ::transpiler::SemOp::" << r.sem
       << "},\n";
  }
  os << "};\n\n";

  if (!suppressed.empty()) {
    os << "// Suppressed duplicates: opcode appeared earlier with a "
          "different\n"
       << "// SemOp; the first binding wins (matches the runtime's\n"
       << "// `DenseMap::try_emplace`). Listed here so the intent is\n"
       << "// discoverable in the generated header.\n";
    for (const auto &[r, winner] : suppressed) {
      os << "//   " << r.opc << " -> " << r.sem
         << "  (suppressed; first binding kept it as " << winner << ")\n";
    }
    os << "\n";
  }
}

static void emitEpilogue(raw_ostream &os, ArrayRef<StringRef> namespaces) {
  for (auto it = namespaces.rbegin(), e = namespaces.rend(); it != e; ++it)
    os << "} // namespace " << *it << "\n";
  os << "\n#endif // AMDGCN_GEN_CANON_TABLE\n";
}

//===----------------------------------------------------------------------===//
// Main generator
//===----------------------------------------------------------------------===//

static void generateCanonTable(const RecordKeeper &records, raw_ostream &os) {
  const Record *salmonOpClass = records.getClass("SalmonOp");
  if (!salmonOpClass)
    PrintFatalError("could not find the `SalmonOp` TableGen class — make "
                    "sure the input includes `SalmonAMDGCN.td`");

  ArrayRef<const Record *> defs = records.getAllDerivedDefinitions("SalmonOp");

  // `getAllDerivedDefinitions` returns records in some internal order; sort
  // by parse-time ID to recover source order so the emitted "first wins"
  // resolution matches the order entries appear in `SalmonAMDGCN.td`.
  SmallVector<const Record *, 1024> sorted(defs.begin(), defs.end());
  llvm::sort(sorted, [](const Record *a, const Record *b) {
    return a->getID() < b->getID();
  });

  SmallVector<Row, 1024> rows;
  rows.reserve(sorted.size());
  // Suppressed duplicate -> name of the SemOp that won.
  SmallVector<std::pair<Row, StringRef>, 4> suppressed;
  // Tracks which opcodes have already been bound, to mirror the
  // `try_emplace`-based "first wins" semantics of the previous runtime.
  StringMap<StringRef> seenOpc;
  for (const Record *rec : sorted) {
    Row r{readInstName(rec), readSemString(rec), rec->getLoc().front()};
    auto it = seenOpc.find(r.opc);
    if (it != seenOpc.end()) {
      // Same SemOp twice on the same opcode is harmless and worth
      // suppressing silently; different SemOps need to be surfaced so
      // the intent is reviewable.
      if (it->second != r.sem)
        suppressed.push_back({r, it->second});
      continue;
    }
    seenOpc.try_emplace(r.opc, r.sem);
    rows.push_back(r);
  }

  // Split the configurable `transpiler::amdgcn::canon` namespace.
  SmallVector<StringRef, 4> nsParts;
  StringRef nsRef = canonNamespace.getValue();
  while (!nsRef.empty()) {
    auto [head, tail] = nsRef.split("::");
    if (!head.empty())
      nsParts.push_back(head);
    nsRef = tail;
  }

  emitPrologue(os, nsParts);
  os << "// " << rows.size() << " entr" << (rows.size() == 1 ? "y" : "ies")
     << " emitted";
  if (!suppressed.empty()) {
    os << "; " << suppressed.size() << " duplicate"
       << (suppressed.size() == 1 ? "" : "s")
       << " suppressed (first-binding-wins)";
  }
  os << ".\n\n";
  emitTable(os, rows, suppressed);
  emitEpilogue(os, nsParts);
}

//===----------------------------------------------------------------------===//
// TableGen registration
//===----------------------------------------------------------------------===//

static TableGen::Emitter::Opt generateCanonTableReg(
    "gen-amdgcn-canon-table", generateCanonTable,
    "Generate the static AMDGCN canonical-opcode -> SemOp table from the "
    "`SalmonOp` records in SalmonAMDGCN.td");
